### ISSUE TITLE
Add styling to new pages

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/instant-website#47]
Follows on from #46 which is merged to `develop`. (Note the modal is now column and the menu breaks on mobile)

Add identical styling to Showcase, About and Terms pages to add a white background and center-align text (so it takes up about 1/3 page on desktop and about full width on mobile). No card needed.

See this for reference:

https://michaelcurrin.github.io/jekyll-blog-demo/about/

Desktop:

![wide](https://user-images.githubusercontent.com/18750745/86540242-ebcb5580-bf03-11ea-84e9-05b1cb701f29.png)

Mobile:
![narrow](https://user-images.githubusercontent.com/18750745/86540239-ea9a2880-bf03-11ea-86a4-12e922f1250a.png)

Lorem ipsum text will do

**Comment by akshay-nm** [comment]
On it

**Comment by MichaelCurrin** [comment]
Closing as the Wiki was a much lower lift https://github.com/MichaelCurrin/instant-website/wiki
